"use client";
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowUpRight, CheckCircle2 } from 'lucide-react';
const services=[
['01','University Admissions','Course selection, university shortlisting, application submission, offer letter guidance, and admission support.','/assets/process/admission.jpg'],
['02','Visa Processing','Student visa preparation, financial verification, interview preparation, lodgement, tracking, and compliance support.','/assets/process/visa%20processing.jpg'],
['03','Documentation Guidance','Complete support for academic documents, financial documents, translations, attestations, and application paperwork.','/assets/process/document%20guide.jpg'],
['04','SOP & Essay Coaching','Personal statements, SOPs, recommendation letters, scholarship essays, and application narratives.','/assets/process/sop.jpg'],
['05','Scholarships & Funding','Scholarship matching, merit-based opportunities, funding guidance, education loan support, and external grants.','/assets/process/Scholarship.jpg'],
['06','IELTS Preparation Classes','Professional IELTS coaching, speaking practice, mock tests, score improvement strategies, and exam readiness.','/assets/process/IELTS.jpg'],
['07','Test Preparation','IELTS, PTE, TOEFL, SAT, GRE, GMAT, and Duolingo preparation with expert trainers.','/assets/process/test%20prep.jpg'],
['08','Pre-Departure Support','Accommodation assistance, airport pickup guidance, banking setup, insurance, travel preparation, and student orientation.','/assets/process/Pre-Departure%20Support.jpg']
];
export default function ServicesPage(){return <main id="main-content" className="pt-28">
 <section className="bg-[#f5f7fb] py-20 lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="eyebrow">Services</p><h1 className="mt-5 max-w-6xl text-6xl font-semibold leading-[.9] tracking-[-.07em] sm:text-8xl">More than an application.<br/><span className="font-serif font-normal italic text-[#087FC1]">A complete journey.</span></h1></div><p className="max-w-xl text-base leading-7 text-slate-500">From the first course search to the day you arrive, Everest Global Network helps make complex decisions feel clear, personal and achievable.</p></div></div></section>
 <section className="bg-white py-16 lg:py-24"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="relative min-h-[480px] overflow-hidden rounded-[34px]"><img src="/assets/students.png" loading="lazy" decoding="async" alt="Students receiving education guidance" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#06162d]/90 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 right-7 text-white sm:left-10 sm:right-10"><span className="text-[9px] font-extrabold uppercase tracking-[.22em] text-[#9db1ff]">Every stage matters</span><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-[.95] tracking-[-.04em] sm:text-5xl">One team beside you from first question to first day on campus.</h2></div></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-[30px] bg-[#06162d] p-8 text-white"><span className="text-6xl font-semibold tracking-[-.06em]">08</span><p className="mt-2 text-sm text-white/50">core service areas, designed to remove friction from the journey.</p></div><div className="rounded-[30px] border border-slate-200 bg-[#f5f6f8] p-8"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#087FC1]">The principle</p><p className="mt-4 text-2xl font-semibold leading-tight tracking-[-.03em]">Good consultancy feels like someone finally made the complicated part simple.</p></div></div></div></div></section>
 <section className="bg-[#f5f6f8] py-16 lg:py-24"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="mb-12 max-w-3xl"><p className="eyebrow">How we help</p><h2 className="mt-4 text-5xl font-semibold leading-[.93] tracking-[-.06em] sm:text-6xl">Eight services. <span className="font-serif font-normal italic text-slate-500">One clear journey.</span></h2></div><div className="grid gap-4 lg:grid-cols-2">{services.map(([n,title,body,image],i)=><motion.article key={n} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} className="group grid overflow-hidden rounded-[30px] border border-slate-200 bg-white md:grid-cols-[.78fr_1.22fr]"><div className="relative min-h-[250px] overflow-hidden"><img src={image} alt={title} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/45 to-transparent"/><span className="absolute left-5 top-5 rounded-full bg-white/90 px-3 py-1.5 text-[9px] font-extrabold tracking-[.16em] text-slate-700">{n}</span></div><div className="flex flex-col p-7 sm:p-8"><div className="flex items-start justify-between gap-4"><h3 className="text-2xl font-semibold tracking-[-.03em]">{title}</h3><ArrowUpRight className="h-5 w-5 shrink-0 text-slate-200 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#087FC1]"/></div><p className="mt-4 text-sm leading-6 text-slate-500">{body}</p><div className="mt-auto pt-7 text-xs font-bold text-[#087FC1]"><CheckCircle2 className="mr-2 inline h-4 w-4"/>Personal guidance</div></div></motion.article>)}</div></div></section>
 <section className="bg-[#06162d] py-20 text-white lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#9db1ff]">One team. Every stage.</p><h2 className="mt-4 text-5xl font-semibold leading-[.9] tracking-[-.06em] sm:text-7xl">A better journey <span className="font-serif font-normal italic text-[#9db1ff]">starts with clarity.</span></h2></div><div><p className="text-sm leading-7 text-white/50">Tell us where you are in your journey and we'll help you work out what matters next.</p><Link href="/contact" className="mt-6 inline-flex rounded-full bg-white px-6 py-4 text-sm font-extrabold text-slate-950">Talk to an expert <ArrowUpRight className="ml-2 h-4 w-4"/></Link></div></div></div></section>
 </main>}
