import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowUpRight, CheckCircle2, Clock3, MapPin } from 'lucide-react';
import { courses, universities } from '@/data/catalog';
import type { Metadata } from 'next';
import { site } from '@/lib/site';
import { Breadcrumbs } from '@/components/Breadcrumbs';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=courses.find(x=>x.slug===slug);if(!c)return {title:'Course not found'};return {title:c.name,description:`Explore ${c.name} at ${c.destination} with Everest Global Network. Get guidance on admissions, requirements and next steps.`,alternates:{canonical:`${site.siteUrl}/courses/${c.slug}`}}}

export function generateStaticParams(){return courses.map(c=>({slug:c.slug}))}
export default async function CourseDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=courses.find(x=>x.slug===slug);if(!c)return notFound();const u=universities.find(x=>x.slug===c.universitySlug);return <main id="main-content" className="pt-32"><section className="mx-auto max-w-[1380px] px-5 pb-14 sm:px-8 lg:px-10"><Breadcrumbs items={[{label:"Courses",href:"/courses"},{label:c.name}]}/><Link href="/courses" className="mt-4 inline-block text-xs font-bold text-slate-400">← Back to courses</Link><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_.42fr] lg:items-end"><div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.16em] text-blue-600">{c.level}</span><h1 className="display mt-6 max-w-5xl text-5xl font-semibold leading-[.92] sm:text-7xl">{c.name}</h1><p className="mt-5 text-sm text-slate-500">{u?.name || c.universitySlug.replaceAll('-',' ')} · {c.destination}</p></div><div className="rounded-[26px] bg-[#061225] p-7 text-white"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-white/40">Tuition</p><p className="mt-2 text-2xl font-semibold">{c.fee||'Contact for fee'}</p><Link href="/contact" className="mt-6 inline-flex rounded-full bg-white px-5 py-3 text-xs font-extrabold text-slate-950">Ask about this course <ArrowUpRight className="ml-1 h-4 w-4"/></Link></div></div></section><section className="bg-[#F7F9FC] py-14 lg:py-20"><div className="mx-auto grid max-w-[1380px] gap-4 px-5 sm:px-8 md:grid-cols-3 lg:px-10"><Stat icon={MapPin} label="Destination" value={c.destination}/><Stat icon={Clock3} label="Duration" value={c.duration}/><Stat icon={CheckCircle2} label="Intake" value={c.intake||'Multiple intakes'}/></div><div className="mx-auto mt-8 max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="rounded-[32px] border border-slate-200 bg-white p-7 sm:p-10"><p className="eyebrow">Course overview</p><p className="mt-5 max-w-4xl text-base leading-8 text-slate-600">{c.description||c.overview||'Explore this programme with Everest Global Network and get personalised guidance on eligibility, application steps and next-stage planning.'}</p></div></div></section></main>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-[24px] border border-slate-200 bg-white p-6"><Icon className="h-5 w-5 text-[#087FC1]"/><p className="mt-6 text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}
