"use client";
import { useState } from "react";
import { ArrowUpRight, Mail, MapPin, Phone, Clock3, CheckCircle2, AlertCircle } from "lucide-react";
import { site } from '@/lib/site';

export default function ContactPage() {
 const [error,setError]=useState(''); const [sent,setSent]=useState(false);
 function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
  event.preventDefault(); setError(''); setSent(false); const form=new FormData(event.currentTarget); const name=String(form.get('name')||'').trim(); const email=String(form.get('email')||'').trim();
  if(name.length<2){setError('Please enter your full name.');return} if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Please enter a valid email address.');return}
  const message=[`Hello ${site.name}, I would like to request a consultation.`,``,`Name: ${name}`,`Email: ${email}`,`Phone: ${form.get('phone')||'Not provided'}`,`Preferred destination: ${form.get('destination')||'Not provided'}`,`What I am looking for: ${form.get('plans')||'Not provided'}`].join('\n');
  const popup=window.open(`https://wa.me/${site.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer'); if(!popup){setError('Your browser blocked the WhatsApp window. Please allow pop-ups or contact us directly using the phone number above.');setSent(false);return} setSent(true);
 }
 return <main id="main-content" className="pt-32"><section className="mx-auto max-w-[1380px] px-5 pb-16 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="eyebrow">Start a conversation</p><h1 className="display mt-4 text-6xl font-semibold leading-[.88] sm:text-8xl">Let's plan<br/><span className="serif italic font-normal text-[#087FC1]">what's next.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-500">Tell us what you are considering. Our team will help you understand your options and decide on a clear next step.</p></div><div className="grid gap-3 sm:grid-cols-2"><Info icon={MapPin} title="visit us" body={site.address}/><Info icon={Phone} title="call" body={site.phone} href={`tel:${site.phone.replace(/\s/g,'')}`}/><Info icon={Mail} title="email" body={site.email} href={`mailto:${site.email}`}/><Info icon={Clock3} title="hours" body={site.hours}/></div></div></section>
 <section className="bg-[#F7F9FC] py-14 lg:py-20"><div className="mx-auto grid max-w-[1380px] gap-5 px-5 sm:px-8 lg:grid-cols-[.75fr_1.25fr] lg:px-10"><div className="rounded-[28px] bg-[#061225] p-8 text-white sm:p-10"><p className="eyebrow-dark">Free consultation</p><h2 className="display mt-5 text-4xl font-semibold leading-[.92] sm:text-6xl">Bring your questions.<br/><span className="serif italic font-normal text-[#B8D8E8]">We'll bring a plan.</span></h2><p className="mt-6 text-sm leading-6 text-white/55">Courses, universities, destinations, documents, visas — start anywhere.</p><div className="mt-10 grid gap-3 text-xs text-white/65"><p><CheckCircle2 className="mr-2 inline h-4 w-4 text-[#6fb9dc]"/>Personal guidance</p><p><CheckCircle2 className="mr-2 inline h-4 w-4 text-[#6fb9dc]"/>Course & university shortlisting</p><p><CheckCircle2 className="mr-2 inline h-4 w-4 text-[#6fb9dc]"/>Application & visa support</p></div></div>
 <form onSubmit={handleSubmit} noValidate className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_20px_70px_rgba(11,27,58,.06)] sm:p-10"><div className="grid gap-4 sm:grid-cols-2"><Field name="name" label="Full name" placeholder="Your name" required/><Field name="email" label="Email" placeholder="you@example.com" type="email" required/><Field name="phone" label="Phone" placeholder="+977 ..."/><Field name="destination" label="Preferred destination" placeholder="Australia, UK..."/></div><Field name="plans" label="What are you looking for?" placeholder="Tell us a little about your plans" textarea/><div aria-live="polite" className="mt-4">{error&&<p className="flex items-center gap-2 text-xs font-semibold text-red-600"><AlertCircle className="h-4 w-4"/>{error}</p>}{sent&&<p className="flex items-center gap-2 text-xs font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Your consultation details are ready in WhatsApp. Send the message to complete the enquiry.</p>}</div><button type="submit" className="mt-5 inline-flex rounded-full bg-[#087FC1] px-6 py-4 text-sm font-bold text-white transition hover:bg-[#066ea8]">Request consultation <ArrowUpRight className="ml-2 h-4 w-4"/></button><p className="mt-3 text-[10px] leading-5 text-slate-400">By submitting, you agree that Everest Global Network may use the information you provide to respond to your enquiry. See our <a className="underline" href="/privacy-policy">Privacy Policy</a>.</p></form></div></section></main>
}
function Info({icon:Icon,title,body,href}:{icon:any;title:string;body:string;href?:string}){const content=<><Icon className="h-4 w-4 text-[#087FC1]"/><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] text-slate-400">{title}</p><p className="mt-1 break-words text-sm font-semibold">{body}</p></>;return href?<a href={href} className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md">{content}</a>:<div className="rounded-2xl border border-slate-200 bg-white p-5">{content}</div>}
function Field({label,placeholder,name,type='text',textarea=false,required=false}:{name:string;label:string;placeholder:string;type?:string;textarea?:boolean;required?:boolean}){return <label className="mt-4 block text-xs font-bold text-slate-600 first:mt-0">{label}{required&&<span className="ml-1 text-[#087FC1]" aria-hidden="true">*</span>}{textarea?<textarea name={name} placeholder={placeholder} required={required} className="mt-2 min-h-28 w-full resize-none rounded-2xl border border-transparent bg-slate-50 p-4 text-sm font-normal outline-none transition focus:border-[#087FC1] focus:bg-white"/>:<input name={name} type={type} placeholder={placeholder} required={required} className="mt-2 h-12 w-full rounded-2xl border border-transparent bg-slate-50 px-4 text-sm font-normal outline-none transition focus:border-[#087FC1] focus:bg-white"/>}</label>}
