import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowUpRight, CheckCircle2, MapPin } from 'lucide-react';
import { destinations } from '@/data/destinations';
import { universities, courses } from '@/data/catalog';
import type { Metadata } from 'next';
import { site } from '@/lib/site';
import { Breadcrumbs } from '@/components/Breadcrumbs';

export async function generateMetadata({params}:{params:Promise<{country:string}>}):Promise<Metadata>{const {country}=await params;const d=destinations.find(x=>x.slug===country);if(!d)return {title:'Destination not found'};return {title:`Study in ${d.country}`,description:`Explore study options in ${d.country}: universities, courses, costs and student guidance from Everest Global Network.`,alternates:{canonical:`${site.siteUrl}/destinations/${d.slug}`}}}
export function generateStaticParams(){return destinations.map(d=>({country:d.slug}))}
export default async function DestinationDetail({params}:{params:Promise<{country:string}>}){const {country}=await params;const d=destinations.find(x=>x.slug===country);if(!d)return notFound();const unis=universities.filter(u=>u.countrySlug===d.slug).slice(0,6);const programs=courses.filter(c=>c.destinationSlug===d.slug).slice(0,6);const cities=[...new Set(universities.filter(u=>u.countrySlug===d.slug).map(u=>u.city))].slice(0,4);return <main id="main-content" className="pt-32"><section className="mx-auto max-w-[1380px] px-5 pb-14 sm:px-8 lg:px-10"><Breadcrumbs items={[{label:'Destinations',href:'/destinations'},{label:d.country}]}/><div className="relative mt-6 min-h-[560px] overflow-hidden rounded-[34px]"><img src={d.image} alt={`${d.country} study destination`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/35 to-black/5"/><div className="relative flex min-h-[560px] max-w-3xl flex-col justify-end p-8 text-white sm:p-12 lg:p-16"><span className="grid h-12 w-12 place-items-center rounded-full bg-white/90 text-2xl text-slate-950">{d.flag}</span><h1 className="display mt-6 text-6xl font-semibold leading-[.88] sm:text-8xl">Study in<br/><span className="serif italic font-normal text-[#B8D8E8]">{d.country}.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-white/70">{d.tagline}</p><Link href="/contact" className="mt-7 inline-flex w-fit rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#061225]">Plan my study journey <ArrowUpRight className="ml-2 h-4 w-4"/></Link></div></div></section>
 <section className="bg-[#F7F9FC] py-14 lg:py-20"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-4 md:grid-cols-3"><Info label="Tuition" value={d.tuition}/><Info label="Living costs" value={d.living}/><Info label="Work rights" value={d.workRights}/></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.75fr]"><div className="rounded-[28px] border border-slate-200 bg-white p-8 sm:p-10"><p className="eyebrow">Why {d.country}</p><p className="mt-5 max-w-4xl text-base leading-8 text-slate-600">{d.overview}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><span className="flex gap-2 text-sm font-semibold"><CheckCircle2 className="h-5 w-5 text-[#087FC1]"/>Post-study opportunities</span><span className="flex gap-2 text-sm font-semibold"><CheckCircle2 className="h-5 w-5 text-[#087FC1]"/>International student community</span></div></div><div className="rounded-[28px] bg-[#061225] p-8 text-white sm:p-10"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/45">Visa note</p><p className="mt-5 text-lg font-semibold leading-7">{d.visaNote}</p><Link href="/contact" className="mt-7 inline-flex text-xs font-bold text-white">Get guidance <ArrowUpRight className="ml-1 h-4 w-4"/></Link></div></div></div></section>
 {cities.length>0&&<section className="bg-white py-20 lg:py-24"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><p className="eyebrow">Popular cities</p><h2 className="mt-3 text-5xl font-semibold tracking-[-.05em]">Find your place in {d.country}.</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cities.map((city,i)=><div key={city} className="border-t border-slate-200 py-6"><span className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">0{i+1}</span><h3 className="mt-3 flex items-center gap-2 text-xl font-semibold"><MapPin className="h-4 w-4 text-[#087FC1]"/>{city}</h3><p className="mt-2 text-xs text-slate-500">Explore universities and programmes in this city.</p></div>)}</div></div></section>}
 <section className="bg-[#F7F9FC] py-20 lg:py-24"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Universities to explore</p><h2 className="mt-3 text-5xl font-semibold">Start your shortlist.</h2></div><Link href="/universities" className="hidden text-sm font-bold sm:block">Browse all ↗</Link></div><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{unis.map(u=><Link key={u.slug} href={`/universities/${u.slug}`} className="group rounded-[24px] border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><span className="text-[9px] font-bold uppercase tracking-[.15em] text-slate-400">{u.city}</span><h3 className="mt-4 text-xl font-semibold">{u.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{u.description}</p><span className="mt-6 inline-flex text-xs font-bold">View university <ArrowUpRight className="ml-1 h-4 w-4"/></span></Link>)}</div></div></section>
 {programs.length>0&&<section className="bg-white py-20 lg:py-24"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><p className="eyebrow">Popular programmes</p><h2 className="mt-3 text-5xl font-semibold">Courses students can explore.</h2><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{programs.map(c=><Link key={c.slug} href={`/courses/${c.slug}`} className="group rounded-[24px] border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><span className="text-[9px] font-bold uppercase tracking-[.15em] text-[#087FC1]">{c.level}</span><h3 className="mt-3 text-lg font-semibold">{c.name}</h3><p className="mt-2 text-xs text-slate-400">{c.duration} · {c.intake||'Flexible intake'}</p><span className="mt-5 inline-flex text-xs font-bold">View programme <ArrowUpRight className="ml-1 h-4 w-4"/></span></Link>)}</div></div></section>}
 <section className="bg-[#0B1B3A] py-20 text-white"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow-dark">Ready when you are</p><h2 className="display mt-4 text-5xl font-semibold leading-[.9] sm:text-7xl">Make {d.country}<br/><span className="serif italic font-normal text-[#B8D8E8]">part of your story.</span></h2></div><Link href="/contact" className="inline-flex rounded-full bg-white px-6 py-4 text-sm font-bold text-slate-950">Talk to an expert <ArrowUpRight className="ml-2 h-4 w-4"/></Link></div></div></section></main>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-[24px] border border-slate-200 bg-white p-6"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">{label}</p><p className="mt-3 text-lg font-semibold">{value}</p></div>}
