"use client";
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowUpRight, Compass, Globe2, GraduationCap, HeartHandshake, ShieldCheck, Target } from 'lucide-react';

const values=[
 {icon:GraduationCap,title:'Student First',body:"Every decision and recommendation is guided by what is best for our students' academic and career goals."},
 {icon:ShieldCheck,title:'Integrity',body:'We provide honest, transparent, and ethical guidance throughout every stage of the study abroad journey.'},
 {icon:Globe2,title:'Global Opportunities',body:'Connecting Nepalese students with world-class universities and international career pathways.'}
];
const milestones=[
 ['01','Expert Counseling','Receive personalized guidance from experienced education counselors who understand your academic and career goals.'],
 ['02','University Partnerships','Access opportunities at leading universities and institutions across multiple study destinations.'],
 ['03','Visa Assistance','Get comprehensive support with documentation, financial planning, and visa application processes.'],
 ['04','Scholarship Guidance','Explore scholarship opportunities and maximize your chances of receiving financial assistance.'],
 ['05','End-to-End Support','From your first consultation to your departure abroad, we guide you every step of the way.'],
 ['06','Student Success Focus','Our success is measured by the achievements and satisfaction of the students we help.']
];
const leadership=[
 ['Mr. Bibek Sharma','founder & principal counsellor','Twenty years across UK and AU admissions; ex-British Council.','/assets/founder.png'],
 ['Mr. Ravi Kishan Yadav','head of admissions and chief coordinator','Guiding students through university admissions and helping them make informed academic decisions.','/assets/raviyadav.png'],
 ['Dhiraj Sah','director, north america','Supporting students pursuing higher education opportunities in the USA and Canada.','/assets/dheraj.png'],
 ['Sandy','head of pre-departure','Logistics, housing and pastoral care lead for 600+ students/year.','/assets/sandy.jpeg']
];
export default function AboutPage(){return <main id="main-content" className="pt-28">
 <section className="bg-[#f5f7fb] py-20 lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[1fr_.72fr] lg:items-end"><div><p className="eyebrow">About Everest Global Network</p><h1 className="mt-5 max-w-5xl text-6xl font-semibold leading-[.9] tracking-[-.07em] text-[#0a1733] sm:text-8xl">Empowering students.<br/><span className="font-serif font-normal italic text-[#087FC1]">Building global futures.</span></h1></div><p className="max-w-xl text-base leading-7 text-slate-500">Helping Nepalese students access world-class education through trusted counseling, university admissions, visa assistance, and personalized support.</p></div></div></section>
 <section className="py-20 lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.88fr_1.12fr] lg:items-center"><div><p className="eyebrow">Who we are</p><h2 className="mt-4 text-5xl font-semibold leading-[.94] tracking-[-.06em] sm:text-6xl">Built on trust, driven by <span className="font-serif font-normal italic text-slate-500">student success.</span></h2><div className="mt-7 space-y-5 text-sm leading-7 text-slate-600"><p>Everest Global Network was established with a simple mission: to provide reliable and student-focused educational counseling for aspiring international students. Over the years, we have grown into a trusted educational consultancy, helping students navigate university admissions, visa applications, scholarships, and pre-departure preparation.</p><p>What began as a vision to support students in achieving their academic goals has evolved into a comprehensive platform connecting Nepalese students with world-class educational opportunities across Australia, Canada, the United Kingdom, the United States, New Zealand, Germany, Japan, and Europe.</p><p>Today, our success is measured not by the number of applications we process, but by the success stories of students who achieve their dreams through our guidance.</p></div></div><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="relative overflow-hidden rounded-[34px] bg-slate-100"><img src="/assets/about.png" loading="lazy" decoding="async" alt="Everest students" className="h-[560px] w-full object-cover"/><div className="absolute inset-x-5 bottom-5 rounded-2xl border border-white/20 bg-[#07152e]/85 p-5 text-white backdrop-blur-xl"><span className="text-[9px] font-bold uppercase tracking-[.2em] text-[#9db1ff]">The Everest promise</span><p className="mt-2 text-lg font-semibold">Clear advice. Human support. Global possibilities.</p></div></motion.div></div></div></section>
 <section className="bg-[#06162d] py-20 text-white lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-px overflow-hidden rounded-[30px] border border-white/10 bg-white/10 lg:grid-cols-3"><Panel title="Mission">To empower Nepalese students with trusted educational guidance and global opportunities, enabling them to achieve academic excellence and successful international careers.</Panel><Panel title="Vision">To become Nepal's most trusted and innovative educational consultancy, helping students access world-class education and build successful futures worldwide.</Panel><div className="bg-[#06162d] p-8 sm:p-10"><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#9db1ff]">Values</p><div className="mt-7 space-y-6">{values.map(v=><div key={v.title} className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white/10"><v.icon className="h-4 w-4"/></span><div><b className="text-sm">{v.title}</b><p className="mt-1 text-sm leading-6 text-white/50">{v.body}</p></div></div>)}</div></div></div></div></section>
 <section className="bg-white py-20 lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="eyebrow">Why students choose us</p><h2 className="mt-4 text-5xl font-semibold leading-[.94] tracking-[-.06em] sm:text-6xl">Six reasons to make a <span className="font-serif font-normal italic text-slate-500">big move</span> with a clear plan.</h2></div><div className="mt-14 grid gap-x-10 gap-y-0 lg:grid-cols-2">{milestones.map(([n,t,b],i)=><motion.div key={n} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}} className="group flex gap-6 border-t border-slate-200 py-8"><span className="text-[10px] font-extrabold tracking-[.2em] text-[#087FC1]">{n}</span><div><h3 className="text-2xl font-semibold tracking-[-.03em]">{t}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">{b}</p></div><ArrowUpRight className="ml-auto h-5 w-5 text-slate-200 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#087FC1]"/></motion.div>)}</div></div></section>
 <section className="bg-[#f5f6f8] py-20 lg:py-28"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Our people</p><h2 className="mt-4 text-5xl font-semibold leading-[.92] tracking-[-.06em] sm:text-6xl">Meet the team behind <span className="font-serif font-normal italic text-slate-500">the journey.</span></h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Experienced counsellors, admissions specialists and pre-departure support working together around each student's goals.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{leadership.map(([name,role,bio,image],i)=><motion.article key={name} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}} className="group overflow-hidden rounded-[28px] border border-slate-200 bg-white"><div className="aspect-[4/4.5] overflow-hidden bg-slate-100"><img src={image} alt={name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><p className="text-[9px] font-semibold lowercase tracking-[.04em] text-[#087FC1]">{role}</p><h3 className="mt-2 text-xl font-semibold">{name}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{bio}</p></div></motion.article>)}</div></div></section>
 <section className="bg-[#087FC1] py-20 text-white"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-white/60">Let's talk</p><h2 className="mt-4 max-w-4xl text-5xl font-semibold leading-[.9] tracking-[-.06em] sm:text-7xl">Your future deserves <span className="font-serif font-normal italic text-white/85">a real plan.</span></h2></div><Link href="/contact" className="inline-flex rounded-full bg-white px-6 py-4 text-sm font-extrabold text-slate-950">Meet the team <ArrowUpRight className="ml-2 h-4 w-4"/></Link></div></div></section>
 </main>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="bg-[#06162d] p-8 sm:p-10"><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#9db1ff]">{title}</p><p className="mt-6 text-xl font-semibold leading-8 text-white/90 sm:text-2xl">{children}</p></div>}
