const sections=[
 ['Website information','The information on this website is provided for general educational guidance. Course availability, fees, entry requirements, intakes, scholarships, university policies and immigration rules can change. Always confirm current requirements with the relevant institution or government authority before making a decision.'],
 ['Consultancy services','Everest Global Network provides education consultancy and guidance services. The exact scope of support depends on the service requested and the student’s circumstances. We aim to provide careful and practical guidance but cannot guarantee admission, scholarships, visa approval, employment, migration outcomes or any particular academic result.'],
 ['Third-party institutions','Universities, colleges, testing organisations, insurers, accommodation providers and government authorities operate independently. Their decisions, fees, timelines, policies and services are outside Everest Global Network’s control.'],
 ['User responsibilities','You are responsible for providing accurate, complete and current information and documents. You should promptly tell us about changes to your circumstances that may affect an application. Submitting false, misleading or fraudulent information may affect your application and the services we can provide.'],
 ['Website use','You may use this website for lawful personal and informational purposes. Do not attempt to disrupt the website, access restricted areas, misuse forms, scrape data in a harmful manner, or infringe intellectual property rights.'],
 ['Intellectual property','Unless otherwise stated, the Everest Global Network brand, original text, design and website materials belong to Everest Global Network or are used with permission. Do not reproduce or commercially reuse them without permission.'],
 ['Changes','We may update the website, services or these terms from time to time. The current version published on this page applies to use of the website after it is posted.']
];
export default function Terms(){return <main id="main-content" className="px-5 pb-24 pt-40"><div className="mx-auto max-w-4xl"><p className="eyebrow">Legal · Last updated September 2026</p><h1 className="display mt-4 text-6xl font-semibold sm:text-8xl">Terms & <span className="font-serif font-normal italic text-[#5F6F85]">Conditions.</span></h1><p className="mt-7 text-base leading-8 text-slate-600">These terms describe the basic rules for using the Everest Global Network website and the nature of the information and consultancy guidance provided through it.</p><div className="mt-14 divide-y divide-slate-200 border-y border-slate-200">{sections.map(([title,body])=><section key={title} className="py-8"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{body}</p></section>)}</div><p className="mt-8 text-xs leading-6 text-slate-400">These website terms are general information and do not replace professional legal or immigration advice where that is required.</p></div></main>}
