import { site } from '@/lib/site';
const sections=[
 ['Information we collect','We may receive information you choose to provide when you contact us, request a consultation, search for study options, or otherwise communicate with Everest Global Network. This can include your name, email address, phone number, study preferences and information contained in your enquiry.'],
 ['How we use information','We use enquiry information to respond to you, provide education consultancy services, discuss courses and universities, coordinate requested support, maintain our website and improve our services. We only use information for purposes reasonably connected with the interaction you have with us.'],
 ['Sharing information','We do not sell personal information. Where necessary to provide a service you request, information may be shared with relevant institutions, service providers or professional partners. We expect such parties to handle information appropriately and only for the relevant purpose.'],
 ['External links and services','Our website may link to universities, social networks, maps, WhatsApp and other third-party services. Their privacy practices are controlled by those providers, so review their policies before submitting information.'],
 ['Data security and retention','We take reasonable technical and organisational measures to protect information. No internet transmission or storage system can be guaranteed to be completely secure. We retain information only for as long as reasonably necessary for the purpose for which it was collected, legitimate business needs, or legal obligations.'],
 ['Your choices','You can ask us what personal information we hold about you, request correction of inaccurate information, or ask us to stop using information for a particular enquiry where applicable. Some records may need to be retained where required by law or for legitimate business purposes.'],
 ['Contact','For privacy questions or requests, contact Everest Global Network at the email address below.']
];
export default function Privacy(){return <main id="main-content" className="px-5 pb-24 pt-40"><div className="mx-auto max-w-4xl"><p className="eyebrow">Legal · Last updated September 2026</p><h1 className="display mt-4 text-6xl font-semibold sm:text-8xl">Privacy <span className="font-serif font-normal italic text-[#5F6F85]">Policy.</span></h1><p className="mt-7 text-base leading-8 text-slate-600">Everest Global Network respects your privacy. This policy explains, in plain language, how we handle information collected through this website and our enquiries.</p><div className="mt-14 divide-y divide-slate-200 border-y border-slate-200">{sections.map(([title,body])=><section key={title} className="py-8"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{body}</p></section>)}</div><p className="mt-8 text-xs leading-6 text-slate-400">Contact: <a className="font-semibold text-[#087FC1]" href={`mailto:${site.email}`}>{site.email}</a> · {site.phone}</p></div></main>}
