import Link from 'next/link';
import { ArrowUpRight, Instagram, Facebook, Mail, MapPin, Phone, MessageCircle } from 'lucide-react';
import { site } from '@/lib/site';

export function Footer(){return <footer className="relative overflow-hidden bg-[#061225] text-white">
 <div className="absolute -left-40 top-0 h-[420px] w-[420px] rounded-full bg-[#087FC1]/10 blur-[120px]" aria-hidden="true"/><div className="absolute -right-40 bottom-0 h-[500px] w-[500px] rounded-full bg-[#087FC1]/[.06] blur-[130px]" aria-hidden="true"/>
 <div className="relative mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-10 lg:py-18">
  <div className="grid gap-12 border-b border-white/10 pb-12 lg:grid-cols-[1.25fr_.7fr_.7fr_.9fr]">
   <div><Link href="/" aria-label="Everest Global Network home" className="inline-block"><img src="/assets/navlogonew.png" loading="lazy" decoding="async" alt="Everest Global Network" className="h-16 w-auto rounded-md bg-white px-2 py-1 object-contain"/></Link><p className="mt-5 max-w-md text-[13px] leading-6 text-white/55">Helping students discover the right course, university and destination — with trusted guidance from first conversation to departure.</p><Link href="/contact" className="mt-6 inline-flex items-center rounded-full bg-white px-5 py-3 text-xs font-bold text-[#061225]">Book a consultation <ArrowUpRight className="ml-2 h-4 w-4"/></Link></div>
   <FooterCol title="Explore"><FooterLink href="/">Home</FooterLink><FooterLink href="/universities">Universities</FooterLink><FooterLink href="/courses">Courses</FooterLink><FooterLink href="/destinations">Destinations</FooterLink><FooterLink href="/services">Services</FooterLink><FooterLink href="/about">About</FooterLink><FooterLink href="/contact">Contact</FooterLink></FooterCol>
   <FooterCol title="Destinations"><FooterLink href="/destinations/australia">Australia</FooterLink><FooterLink href="/destinations/uk">United Kingdom</FooterLink><FooterLink href="/destinations/canada">Canada</FooterLink><FooterLink href="/destinations/usa">United States</FooterLink><FooterLink href="/destinations/germany">Germany</FooterLink><FooterLink href="/destinations/newzealand">New Zealand</FooterLink></FooterCol>
   <div><p className="footer-head">Connect</p><div className="grid gap-3 text-[13px] leading-5 text-white/55"><a className="flex gap-3 hover:text-white" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(site.address)}`} target="_blank" rel="noreferrer"><MapPin className="h-4 w-4 shrink-0 text-[#6fb9dc]"/> {site.address}</a><a className="flex gap-3 hover:text-white" href={`tel:${site.phone.replace(/\s/g,'')}`}><Phone className="h-4 w-4 shrink-0 text-[#6fb9dc]"/> {site.phone}</a><a className="flex gap-3 break-all hover:text-white" href={`mailto:${site.email}`}><Mail className="h-4 w-4 shrink-0 text-[#6fb9dc]"/> {site.email}</a></div><div className="mt-6 flex gap-2"><Social icon={Instagram} href={site.instagram} label="Instagram"/><Social icon={Facebook} href={site.facebook} label="Facebook"/><Social icon={MessageCircle} href={`https://wa.me/${site.whatsapp}`} label="WhatsApp"/></div></div>
  </div>
  <div className="flex flex-col justify-between gap-4 pt-6 text-[10px] text-white/35 sm:flex-row"><span>© {new Date().getFullYear()} Everest Global Network. All rights reserved.</span><div className="flex flex-wrap gap-x-5 gap-y-2"><Link href="/privacy-policy" className="hover:text-white/70">Privacy Policy</Link><Link href="/terms-conditions" className="hover:text-white/70">Terms & Conditions</Link><Link href="/cookie-policy" className="hover:text-white/70">Cookie Policy</Link></div></div>
 </div>
 </footer>}
function FooterCol({title,children}:{title:string;children:React.ReactNode}){return <div><p className="footer-head">{title}</p><div className="grid gap-2.5 text-[13px]">{children}</div></div>}
function FooterLink({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="text-white/55 transition-colors hover:text-white">{children}</Link>}
function Social({icon:Icon,href,label}:{icon:any;href:string;label:string}){return <a href={href} target="_blank" rel="noreferrer" aria-label={label} title={label} className="grid h-9 w-9 place-items-center rounded-full border border-white/10 bg-white/5 text-white/55 transition hover:-translate-y-0.5 hover:bg-white/10 hover:text-white"><Icon className="h-4 w-4"/></a>}
