"use client";
import Link from "next/link";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Search, Menu, X, ChevronDown, ArrowUpRight } from "lucide-react";
import { destinations } from "@/data/destinations";

export function Navbar(){
 const [open,setOpen]=useState(false); const [destOpen,setDestOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [q,setQ]=useState("");
 const nav=[{label:"Home",href:"/"},{label:"Universities",href:"/universities"},{label:"Courses",href:"/courses"}];
 const submit=(e:React.FormEvent)=>{e.preventDefault();window.location.href=`/courses${q.trim()?`?q=${encodeURIComponent(q.trim())}`:""}`;setSearchOpen(false)};
 return <header className="fixed inset-x-0 top-0 z-50 px-3 pt-3 sm:px-5"><a href="#main-content" className="skip-link">Skip to content</a>
  <nav aria-label="Primary navigation" className="mx-auto flex h-[76px] max-w-[1440px] items-center gap-3 rounded-[22px] border border-slate-200/90 bg-white/95 px-3 shadow-[0_14px_50px_rgba(11,23,48,.08)] backdrop-blur-xl sm:px-5">
   <Link href="/" className="shrink-0" aria-label="Everest Global Network home"><img src="/assets/navlogonew.png" alt="Everest Global Network" className="h-[48px] w-auto object-contain sm:h-[54px]"/></Link>
   <div className="mx-auto hidden items-center gap-0.5 xl:flex">
    {nav.map(x=><Link key={x.href} href={x.href} className="nav-link">{x.label}</Link>)}
    <div className="relative" onMouseEnter={()=>setDestOpen(true)} onMouseLeave={()=>setDestOpen(false)}>
      <button aria-expanded={destOpen} aria-haspopup="menu" className="nav-link flex items-center gap-1">Destinations <ChevronDown className="h-3.5 w-3.5"/></button>
      <AnimatePresence>{destOpen&&<motion.div role="menu" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} className="absolute left-1/2 top-full mt-3 w-[470px] -translate-x-1/2 rounded-[24px] border border-slate-200 bg-white p-3 shadow-[0_30px_90px_rgba(11,23,48,.16)]">
       <div className="mb-2 flex items-center justify-between px-2 py-2"><div><span className="block text-[10px] font-bold uppercase tracking-[.2em] text-[#087FC1]">Study destinations</span><span className="mt-1 block text-xs text-slate-400">Choose where your next chapter begins.</span></div><Link href="/destinations" className="text-xs font-bold text-slate-900">View all ↗</Link></div>
       <div className="grid grid-cols-2 gap-1">{destinations.map(d=><Link role="menuitem" key={d.slug} href={`/destinations/${d.slug}`} className="flex items-center gap-3 rounded-2xl p-2.5 transition hover:bg-slate-50"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-slate-200 bg-slate-50 text-[21px] leading-none" aria-hidden="true">{d.flag}</span><span><b className="block text-sm text-slate-900">{d.country}</b><small className="text-[10px] text-slate-400">Universities · Courses</small></span></Link>)}</div>
      </motion.div>}</AnimatePresence>
    </div>
    <Link href="/services" className="nav-link">Services</Link><Link href="/about" className="nav-link">About</Link><Link href="/contact" className="nav-link">Contact</Link>
   </div>
   <div className="ml-auto flex items-center gap-2">
    <button type="button" onClick={()=>setSearchOpen(true)} aria-label="Find your dream course" className="hidden h-11 w-[205px] items-center rounded-full border border-slate-200 bg-slate-50 px-4 text-left lg:flex 2xl:w-[245px]"><Search className="h-4 w-4 shrink-0 text-slate-400"/><span className="ml-2 truncate text-[11px] font-medium text-slate-500">Find your dream course</span></button>
    <Link href="/contact" className="hidden rounded-full bg-[#087FC1] px-5 py-3.5 text-[11px] font-bold text-white shadow-lg shadow-blue-500/15 transition hover:-translate-y-0.5 hover:bg-[#066ea8] sm:inline-flex">Book a consultation <ArrowUpRight className="ml-1.5 h-4 w-4"/></Link>
    <button aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="grid h-11 w-11 place-items-center rounded-full bg-[#0B1B3A] text-white xl:hidden">{open?<X className="h-5 w-5"/>:<Menu className="h-5 w-5"/>}</button>
   </div>
  </nav>
  <AnimatePresence>{open&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="mx-auto mt-2 max-w-[1440px] rounded-[24px] border border-slate-200 bg-white p-3 shadow-2xl xl:hidden"><button type="button" onClick={()=>setSearchOpen(true)} className="mb-2 flex h-12 w-full items-center rounded-2xl bg-slate-50 px-4 text-left"><Search className="h-4 w-4 text-slate-400"/><span className="ml-3 text-sm text-slate-500">Find your dream course</span></button><div className="grid gap-1">{[...nav,{label:"Destinations",href:"/destinations"},{label:"Services",href:"/services"},{label:"About",href:"/about"},{label:"Contact",href:"/contact"}].map(x=><Link key={x.href} onClick={()=>setOpen(false)} href={x.href} className="rounded-2xl px-4 py-3.5 text-sm font-bold hover:bg-slate-50">{x.label}</Link>)}</div><Link onClick={()=>setOpen(false)} href="/contact" className="mt-2 flex justify-center rounded-2xl bg-[#087FC1] px-4 py-4 text-sm font-bold text-white">Book a consultation</Link></motion.div>}</AnimatePresence>
  <AnimatePresence>{searchOpen&&<motion.div className="fixed inset-0 z-[80] bg-[#061225]/50 p-4 backdrop-blur-md sm:p-8" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="mx-auto mt-[8vh] max-w-3xl rounded-[28px] bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">Course discovery</p><h2 className="mt-2 text-2xl font-semibold">Find your dream course</h2></div><button onClick={()=>setSearchOpen(false)} aria-label="Close search" className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><X className="h-4 w-4"/></button></div><form onSubmit={submit} className="mt-6 flex items-center rounded-2xl bg-slate-50 px-4"><Search className="h-5 w-5 text-slate-400"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} className="h-14 w-full bg-transparent px-3 text-sm outline-none" placeholder="Computer Science, MBA, Nursing..." aria-label="Search courses, universities or subjects"/><button className="rounded-xl bg-[#087FC1] px-4 py-2.5 text-xs font-bold text-white">Search</button></form><div className="mt-6 grid gap-6 sm:grid-cols-2"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">Popular subjects</p><div className="mt-3 flex flex-wrap gap-2">{['Computer Science','Business','Engineering','Healthcare','Law','Accounting'].map(x=><button key={x} onClick={()=>setQ(x)} className="rounded-full border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-[#087FC1] hover:text-[#087FC1]">{x}</button>)}</div></div><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">Explore</p><div className="mt-3 grid gap-2 text-sm font-semibold"><Link onClick={()=>setSearchOpen(false)} href="/universities" className="rounded-xl bg-slate-50 px-4 py-3 hover:bg-slate-100">Universities →</Link><Link onClick={()=>setSearchOpen(false)} href="/destinations" className="rounded-xl bg-slate-50 px-4 py-3 hover:bg-slate-100">Destinations →</Link></div></div></div></div></motion.div>}</AnimatePresence>
 </header>
}
